### ISSUE TITLE
Proposal: Call each `g.actors` `.interrupt(err)` method in reverse 

### ISSUE THREAD

**Issue by chilts** [oklog/run#11]
Firstly, I've just converted a small project over to use `run.Group()` and I love it - so thank you.

For the project, there will be a number of long running top-level actors hence this package is pretty much perfect. The way we construct these actors, is "in the order dictated by their dependency relationships" (as quoted from here https://blog.gopheracademy.com/advent-2017/run-group/). This works because the `g.actors` `.execute()` functions are called in order. 

But (just like `defer` in some ways) it might make sense to call the `g.actors` `.interrupt(err)` functions in reverse order so the later actors that depend on the former actors are closed down and tidied up first, with the actors at the base of the relationships being closed last.

Your thoughts appreciated and apologies for opening a mostly inconclusive issue on a small, well used, and mature project.

**Comment by chilts** [comment]
Closing this so it doesn't clog up the issues. Feel free to re-open if you're happy to provide thoughts or feedback. I'll assume it wasn't a great idea. :)

**Comment by burdiyan** [comment]
Found this after I realized closing was done in a non-reverse order which is what I was expecting. 

> I'll assume it wasn't a great idea. :)

@chilts Why have you thought that?

**Comment by peterbourgon** [comment]
Note that the order in which the interrupt functions are called is actually not defined and so shouldn't be relied upon :) 

If your run.Group needs shutdown to happen in a particular way, you should orchestrate that behavior yourself.

**Comment by cbrake** [comment]
After working with this a bit, I've realized the best scenario is where there are no ordering requirements between processes -- this is a useful constraint which pushes you in the right direction. If there are dependencies, then handle this in the processes themselves if possible.

https://community.tmpdir.org/t/structuring-go-apps-for-testing-and-lifecycle-management-the-start-stop-pattern/550
