### ISSUE TITLE
Implement GracefulRestart actor

### ISSUE THREAD

**Issue by sagikazarmark** [oklog/run#15]
I regularly use run and [tableflip](https://github.com/cloudflare/tableflip) together in systemd managed applications for graceful restarts.

Would you be interested in adding support for it?

The actor does not actually require to import tableflip as a dependency. Here is the current code: https://github.com/sagikazarmark/appkit/blob/master/run/upgrade.go

I'd be happy to send a PR if you like it.

**Comment by peterbourgon** [comment]
Interesting. Please do! I have one comment/question on the code which I'll save for the PR.

**Comment by sagikazarmark** [comment]
Opened a PR with the current code. Not sure how to properly test this though...
