### ISSUE TITLE
Best way to not call interrupt functions when "err = nil"

### ISSUE THREAD

**Issue by sneko** [oklog/run#17]
Hi @peterbourgon ,

Thanks so much for this library, it's really easy to use and it's been a while for me now 👍 

I have a specific question, as soon as an `execute` function will return, the `run.Group` will call each `interrupt` function even if there is no error.

In my case I have a service manager that accepts you to add your own module as soon as you "implement" some functions like "Start/Stop/Ready...". That's great to supervise all modules and terminate them properly when needed.

My only concern is when someone implement a `Start()` that is none-blocking (but that needs to be considered as a module), on my side I will add it to the `run.Group` but since it returns `nil` just after the group starts, it interrupts all other modules.

The solution I see right now is to make modules explicitly implement a function `IsSynchronous() bool` and if yes, I execute the `Start()` directly without adding it to the `run.Group`.

I could otherwise tell module developers the Start() is required to be async and they would implement empty channel to block... but I feel like it's not a proper way.

If you have any suggestion, I'm interested 😄 (maybe I need to redesign having "generic" modules to manage)

Thank you!

**Comment by peterbourgon** [comment]
The run.Group _requires_ all execute functions to be blocking. That's an invariant of the design. Assuming your module has some function like Wait, which will block until the Started goroutine has been Stopped, you can adapt it like this:

```go
m := NewModule()
g.Add(func() error {
    m.Start()
    return m.Wait()
}, func(error) {
    m.Stop()
})
```

If there is no function like Wait, then your code is incompatible with this package — and also badly designed! :) It's important that components have some way of signaling to their callers that their execution has been stopped.

Hope that helps.

**Comment by peterbourgon** [comment]
Or maybe to respond to a different part of your question:

> I have a specific question, as soon as an execute function will return, the run.Group will call each interrupt function even if there is no error.

That's the desired/expected behavior. A run.Group binds the fate of all actors together. The semantic is that when any one of them dies, all of them should die; the initial terminating error is merely a detail.

**Comment by sneko** [comment]
Thank you for your answer Peter! I will adjust my code to make it compatible 👍
