### ISSUE TITLE
Handle second SIGINT

### ISSUE THREAD

**Issue by sagikazarmark** [oklog/run#19]
Applications often listen to additional interrupt signals after the first one and terminate the application (with exit code 2) if it fails to gracefully stop after the first signal.

Do you think it would make sense in run as well?

**Comment by peterbourgon** [comment]
Huh, I've never seen or heard about this. Do you have something I can read about it?

**Comment by peterbourgon** [comment]
It would be easy to implement yourself, though...

```go
{
    ctx, cancel := context.WithCancel(context.Background())
    g.Add(func() error {
        c := make(chan os.Signal, 1)
        signal.Notify(c, syscall.SIGUSR1)
        select {
        case <-c:
            return ErrUSR1
        case <-ctx.Done():
            return ctx.Err()
        }
    }, func(error) {
        cancel()
    })
}
{
    ctx, cancel := context.WithCancel(context.Background())
    g.Add(func() error {
        c := make(chan os.Signal, 1)
        signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)
        select {
        case <-c:
            return ErrINT
        case <-ctx.Done():
            return ctx.Err()
        }
    }, func(error) {
        cancel()
    })
}
err := g.Run()
switch {
case errors.Is(err, ErrINT):
    os.Exit(1)
case errors.Is(err, ErrUSR1):
    os.Exit(2)
case err != nil:
    os.Exit(3)
case err == nil:
    os.Exit(0)
}
```

**Comment by sagikazarmark** [comment]
> Do you have something I can read about it?

I've actually observed this behavior in a bunch of tools recently. For example, most of Hashicorp's tooling, like Terraform works like that. I guess it makes sense when there is a potentially a long shutdown period.

I think your example is slightly different from what I wanted to describe. The idea is that a second signal would immediately terminate the application (i.e. call `os.Exit`) terminating any long running shutdown procedure.

TBH, I've implemented it and it turned out to be less useful than I thought, so I don't use it anymore. (It seemed useful in a development environment, but graceful termination doesn't really matter in dev, so I can just kill it and move on)

**Comment by peterbourgon** [comment]
> a second signal would immediately terminate the application (i.e. call os.Exit) terminating any long running shutdown procedure

Ah, as in a second ctrl-C during a shutdown process would terminate the shutdown process immediately?

**Comment by sagikazarmark** [comment]
Yes

**Comment by peterbourgon** [comment]
So basically the idea is

```go
package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"time"

	"github.com/oklog/run"
)

func main() {
	log.Printf("starting...")
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		c := make(chan os.Signal, 1)
		signal.Notify(c, os.Interrupt)
		first := <-c
		log.Printf("got %s, sending cancel signal...", first)
		cancel()
		second := <-c
		log.Printf("got %s again, terminating immediately", second)
		os.Exit(2)
	}()
	log.Print(exec(ctx))
}

func exec(ctx context.Context) error {
	var g run.Group
	g.Add(run.SignalHandler(ctx))
	err := g.Run()
	log.Printf("error: %v; waiting 3s then returning...", err)
	time.Sleep(3 * time.Second)
	return nil
}
```

Can you suggest a way to provide that functionality cleanly in the module?

**Comment by sagikazarmark** [comment]
Can't say I see a "clean" way to do it. Best guess is a second groutine inside the signal handler func that continues listening to the signal channel.

But it should probably be optional, so it would require configuration....

I realized that I primarily wanted this feature for local development, because orchestrators will send a kill signal after a certain time anyway.

**Comment by peterbourgon** [comment]
Here's a slightly more realistic example...

```go
package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/oklog/run"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		c := make(chan os.Signal, 1)
		signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)
		first := <-c
		log.Printf("\ngot first signal (%s) - soft shutdown", first)
		cancel()
		second := <-c
		log.Printf("\ngot second signal (%s) - hard shutdown", second)
		os.Exit(1)
	}()
	log.Printf("starting...")
	err := exec(ctx)
	log.Printf("done with err=%v", err)
}

func exec(ctx context.Context) error {
	var g run.Group

	// subctx will get canceled when this actor's interrupt func is called, or
	// the ctx passed to exec is canceled. And we've set it up so that parent
	// ctx is canceled on ctrl-C.
	subctx, cancel := context.WithCancel(ctx)
	g.Add(func() error {
		<-subctx.Done()
		return subctx.Err()
	}, func(error) {
		cancel()
	})

	server := &http.Server{
		Addr:    "localhost:8080",
		Handler: http.HandlerFunc(handle),
	}

	g.Add(func() error {
		log.Printf("ListenAndServe...")
		err := server.ListenAndServe()
		log.Printf("ListenAndServe returned with err=%v", err)
		return err
	}, func(err error) {
		log.Printf("server received interrupt request with err=%v", err)
		grace := 3 * time.Second
		ctx, cancel := context.WithTimeout(context.Background(), grace)
		log.Printf("Shutdown initiated with grace period %s...", grace)
		err = server.Shutdown(ctx)
		log.Printf("Shutdown returned with err=%v", err)
		cancel()
	})

	return g.Run()
}

func handle(w http.ResponseWriter, r *http.Request) {
	d := r.URL.Query().Get("d")
	delay, _ := time.ParseDuration(d)
	if delay == 0 {
		delay = time.Second
	}

	log.Printf("%s: %s: %s: start", r.RemoteAddr, r.URL, delay)

	select {
	case <-time.After(delay):
		log.Printf("%s: %s: %s: elapsed", r.RemoteAddr, r.URL, delay)
	case <-r.Context().Done():
		log.Printf("%s: %s: %s: canceled", r.RemoteAddr, r.URL, delay)
	}
}
```

The critical thing being that the signal.Notify is done _above_ the group and transformed into a context cancelation, and the cancelation is what the group actually sees. I could envision adding some kind of helper functionality to package run that provided this scaffolding, e.g.

```go
package run

func Interruptable(ctx context.Context, onFirst, onSecond func(os.Signal), signals ...os.Signal) context.Context {
	ctx, cancel := context.WithCancel(ctx)
	go func() {
		c := make(chan os.Signal, 1)
		signal.Notify(c, signals...)
		onFirst(<-c)
		cancel()
		onSecond(<-c)
		os.Exit(2)
	}()
	return ctx
}
```

But that feels too... rigid? Why just two phases? Shouldn't the os.Exit be user-configurable instead of hard-coded? So then it probably should generalize to something like e.g.

```go
package run

type PhaseFunc func(sig os.Signal, cancel func())

func Interruptable(ctx context.Context, signals []os.Signal, phases []PhaseFunc) context.Context {
	ctx, cancel := context.WithCancel(ctx)
	go func() {
		c := make(chan os.Signal, 1)
		signal.Notify(c, signals...)
		for _, phase := range phases {
			phase(<-c, cancel)
		}
	}()
	return ctx
}
```

Which would then need to be used like

```go
func main() {
	var (
		signals = []os.Signal{syscall.SIGINT, syscall.SIGTERM}
		soft    = func(sig os.Signal, cancel func()) { log.Printf("got %s, soft shutdown...", sig); cancel() }
		hard    = func(sig os.Signal, _ func())     { log.Printf("got %s, hard shutdown...", sig); os.Exit(2) }
		phases = []run.PhaseFunc{soft, hard}
		ctx     = run.Interruptable(context.Background(), signals, phases)
	)
	log.Printf("starting...")
	err := exec(ctx)
	log.Print("done with err=%v", err)
}
```

But that doesn't feel like it adds much value versus the original code to me.

**Comment by burdiyan** [comment]
The way I normally achieve this behavior is by calling `signal.Stop(c)` after the first signal is received on `c`.

**Comment by peterbourgon** [comment]
Won't that cause a second ctrl-C to just hard-kill the program?

**Comment by burdiyan** [comment]
That's right. I believe this is what this issue was originally about?

Although I probably misread that, because @sagikazarmark expected the second SIGINT to cause program to exit with code 2, and with hard-kill it will still exit with code 1.

I do agree with @sagikazarmark in that I too often see programs behave like that, and I think it's useful: first SIGINT begins graceful shutdown, and the second time you press ctrl+c it would force kill the program.
