### ISSUE TITLE
Any reason why interrupt functions are executed synchronously?

### ISSUE THREAD

**Issue by sneko** [oklog/run#22]
Hi @peterbourgon ,

Long time since my last question but... I just faced an issue. Context:

* I use your library to deal with multiple modules
* when a SIGTERM is received, the group is supposed to interrupt all actors
* it always worked in the past but... today I got into troubles
* one of my interrupt has "httpServer.Shutdown(ctx)" which waits for all connections to be closed (but it could the same for grpcServer.GracefulStop())

Today, one of my graceful methods to close connections got stuck... and since all interrupts are called in a synchronous for (https://github.com/oklog/run/blob/master/group.go#L45-L48), the rest of the actors were still running until... the supervisor (Kubernetes) decided the application had reached the time limit to shut down... and simply SIGKILL the program.

It has left some modules not closing... (it seems nothing too bad but that's annoying).

**I would like to understand why the interrupt functions are not called into multiple goroutines?** Still by switching to async interruptions a module would have not been closed (the blocking one), but at least the rest of actors could have.

_Since I cannot reproduce my issue (the Kubernetes time limit was 30s, I don't know any request lasting for so long, and I have no websocket... I cannot exactly explain what happened), I will probably try to play with a `context.WithCancel(ctx)` for the HTTP servers when closing `.Shutdown(ctx)`, and for the gRPC, launch aside the `.GracefulStop()` a goroutine so after X seconds if still not closed it will just `.Close()` the server (abruptly)._ But in addition depending on your answer, I could also fork your library to do async interruptions... having your thoughts could help 😃 👍 

Thank you,

**Comment by peterbourgon** [comment]
Interrupt funcs are run one after the other so that the behavior of the package is deterministic. That's important. But if it's a problem for you, you don't need to fork the library to solve it :) [The rule for the interrupt func](https://pkg.go.dev/github.com/oklog/run#Group.Add) is that

> Each actor must be pre-emptable by an interrupt function. That is, if interrupt is invoked, execute should return. Also, it must be safe to call interrupt even after execute has returned.

That's it. So they don't need to block.

As you observe, you should definitely pass http.Server.Shutdown a context with a timeout built in to it. So right now you might have e.g.

```go
g.Add(func() error {
    return server.ListenAndServe(...)
}, func(error) {
    ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
    server.Shutdown(ctx)
    cancel()
})
```

But even that can block for up to 3 seconds. So if you want to avoid that you can do e.g.

```go
g.Add(func() error {
    return server.ListenAndServe(...)
}, func(error) {
    go func() {
        ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
        server.Shutdown(ctx)
        cancel() 
    }()
})
```

which should work just as well.

**Comment by peterbourgon** [comment]
Does that help?

**Comment by sneko** [comment]
Indeed, it makes totally sense being able to use goroutine into `interrupt` since `.Run()` will always wait for all `execute` to return.

Thank you very much Peter  👍
