### ISSUE TITLE
Problematic licensing

### ISSUE THREAD

**Issue by cgt** [oklog/run#4]
Allow me to apologize in advance for opening an issue about licensing lest it be considered bikeshedding.

Please consider changing the license from Apache 2.0 (AL2) to a freer and simpler license such as the 2 or 3 clause BSD licenses or the MIT license. Unfortunately, AL2 is incompatible with GPLv2, cutting off AL2-licensed and GPLv2-licensed projects from each other, splitting the open source ecosystem. This needless conflict is contrary to the purpose of a permissive license: unencumbered sharing and cooperation.

Additionally, AL2 is long and verbose, and its [book-keeping clause](https://github.com/oklog/run/commit/b4de77a4bfac5ba50e8881838cc6f3961cfdc222#diff-9879d6db96fd29134fc802214163b95aR97) is yet more bureaucracy for developers to waste their time and screen space on. Seeing as you have not included the massive AL2 license header in the source files, as suggested in AL2's appendix, I take it you prefer your source files to contain source code, not bureaucratic boilerplate like license headers and obligatory "prominent notices" stating that the file has been changed by so-and-so.

[Truly permissive](http://copyfree.org/) licenses, such as the BSD and MIT licenses, do not have these problems, allowing developers to focus on software rather than legal headaches.

**Comment by cbandy** [comment]
From GNU's list of [GPL-Compatible Free Software Licenses](https://www.gnu.org/licenses/license-list.en.html):

[Apache License, Version 2.0](https://www.gnu.org/licenses/license-list.en.html#apache2)
> This is a free software license, compatible with version 3 of the GNU GPL.
> 
> Please note that this license is not compatible with GPL version 2, because it has some requirements that are not in that GPL version. These include certain patent termination and indemnification provisions. The patent termination provision is a good thing, which is why we recommend the Apache 2.0 license for substantial programs over other lax permissive licenses.

[Modified BSD license](https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD)
> This is the original BSD license, modified by removal of the advertising clause. It is a lax, permissive non-copyleft free software license, compatible with the GNU GPL.
> 
> This license is sometimes referred to as the 3-clause BSD license.
> 
> The modified BSD license is not bad, as lax permissive licenses go, though the Apache 2.0 license is preferable. However, it is risky to recommend use of “the BSD license”, even for special cases such as small programs, because confusion could easily occur and lead to use of the flawed [_original_ BSD license](https://www.gnu.org/licenses/license-list.en.html#OriginalBSD). To avoid this risk, you can suggest the X11 license instead. The X11 license and the modified BSD license are more or less equivalent.
> 
> However, the Apache 2.0 license is better for substantial programs, since it prevents patent treachery.

[FreeBSD license](https://www.gnu.org/licenses/license-list.en.html#FreeBSD)
> This is the original BSD license with the advertising clause and another clause removed. (It is also sometimes called the “2-clause BSD license”.) It is a lax, permissive non-copyleft free software license, compatible with the GNU GPL.
> 
> Our comments about the [Modified BSD license](https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD) apply to this license too.

[Expat License](https://www.gnu.org/licenses/license-list.en.html#Expat)
> This is a lax, permissive non-copyleft free software license, compatible with the GNU GPL. It is sometimes ambiguously referred to as the _MIT License_.
> 
> For substantial programs it is better to use the Apache 2.0 license since it blocks patent treachery.

[X11 License](https://www.gnu.org/licenses/license-list.en.html#X11License)
> This is a lax permissive non-copyleft free software license, compatible with the GNU GPL. Older versions of XFree86 used the same license, and some of the current variants of XFree86 also do. Later versions of XFree86 are distributed under the [XFree86 1.1 license](https://www.gnu.org/licenses/license-list.en.html#XFree861.1License).
> 
> This license is sometimes called the _MIT license_, but that term is misleading, since MIT has used many licenses for software.
> 
> This is a fine license for a small program. A larger program usually ought to be copyleft; but if you are set on a lax permissive license for one, we recommend the Apache 2.0 license since it protects users from patent treachery.

**Comment by apotheon** [comment]
I would be careful about taking advice for license selection from GNU, in this case particularly with regard to its references to AL2.  The GNU project has shown itself quite willing, even eager, to create widespread license incompatibility issues, and quite unwilling to do anything to resolve them, if those issues are a consequence of pursuing a self-aggrandizing agenda.  Whether you believe in the ideals on which the GNU project was founded, its current management and practices leave something to be desired in the realm of high ideals.

License incompatibility is one of the worst problems for the open source world, as aptly demonstrated by such events as the conflict the SFLC initiated against Canonical last year over the matter of GPL and CDDL compatibility interpretations.  Avoiding license incompatibilities is incredibly important for the health and advancement of open source ideals and development success.  Any perceived benefit of the Apache License version 2 can be had with some other, more widely compatible license except length, complexity, and density of legalese.

**Comment by peterbourgon** [comment]
No, thank you.

**Comment by sboosali** [comment]
> The GNU project has shown itself quite willing, even eager, to create widespread license incompatibility issues, and quite unwilling to do anything to resolve them, if those issues are a consequence of pursuing a self-aggrandizing agenda

that's a lot of accusations ("self-aggrandizing") without any evidence. 

also, the Apache License is compatible with GPL.
