### ISSUE TITLE
This package is only remotely similar to errgroup

### ISSUE THREAD

**Issue by bep** [oklog/run#9]
Note that I'm sure this is due to not understanding this, but  I hope then that my feedback can maybe help improve the docs/examples.

I have used `errgroup` -- where the semantics is:

>The first call to return a non-nil error cancels the group; its error will be returned by Wait.

The tests/examplesn in this repo with multiple coordinated goroutines seem to focus on the `error` case and not so much on the happy case.

I adjusted the `TestMany` test to not return any errors, and I find it surprising that it fails:

```go
func TestManyOK(t *testing.T) {
	var g run.Group
	g.Add(func() error { return nil }, func(error) {})
	cancel := make(chan struct{})
	counter := 0
	g.Add(func() error {
		for i := 0; i < 100; i++ {
			counter++
			// Do some work
			strings.Repeat("a", 3000)
			select {
			case <-cancel:
				return nil
			default:
			}
		}
		return nil
	}, func(err error) {
		close(cancel)
	})

	res := make(chan error)
	go func() { res <- g.Run() }()
	select {
	case err := <-res:
		if err != nil {
			t.Error("got error:", err)
		}
		if counter != 100 {
			t.Error("got", counter)

		}
	case <-time.After(100 * time.Millisecond):
		t.Error("timeout")
	}
}

```

**Comment by peterbourgon** [comment]
run.Group is designed for essentially permanent actors. Any returning actor is interpreted as a signal to tear down the others.

**Comment by peterbourgon** [comment]
I would gladly take a pithy PR to the docs to make this more explicit.

**Comment by bep** [comment]
>I would gladly take a pithy PR to the docs to make this more explicit.

I'm not sure about the "more explicit" part, as it is now it is just plain wrong:

>Package run is somewhat similar to package errgroup, except it doesn't require actor goroutines to understand context semantics.

This package is only "remotely similar" to `errgroup` -- so the docs should be fixed to save potential confusion from others. I'll leave this issue open in case you or others want to get it right.

**Comment by peterbourgon** [comment]
Respectfully, your conclusion is overly pedantic. The current behavior is well-described by the documentation and I don’t believe further changes are necessary.

**Comment by bep** [comment]
Respectfully, your reply is overly ignorant and possibly arrogant.  I came here from a Tweet you made selling this as a "better errgroup", which it isn't. It's something very different.  The current description is wasting peoples' time. But now they at least have this issue to clear up their confusion. Have a nice weekend! 

Oh, I agree with you that the new `errors` package API scheduled for Go 1.13 is very confusing, but it is clarity compared to this package :-)

**Comment by bep** [comment]
>Respectfully, your conclusion is overly pedantic.

I was pointed to this repo by a Tweet from you about this project being a "better errgroup". Given that, my conclusion is very much practical.
